version: '3.7'

services:
  db:
    build: ./
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cat
      - POSTGRES_PASSWORD=meow

volumes:
  postgres_data:

